### ISSUE TITLE
Improve Docs Meta

### ISSUE THREAD

**Issue by JulesLagadic** [Scalingo/documentation#288]
- [ ] remove meta keywords
- [ ] add lang attribute to html tag
- [ ] description can be up to 300 characters (limit set to 160 actually ?)
- [ ] write a custom description between 250 and 300 characters for index (https://doc.scalingo.com/)

**Comment by yannski** [comment]
@JulesLagadic what do you propose for the description of the index page?
